### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#13]
The few functions and methods which have been defined should have documentation. These could be auto-generated from their docstrings using something like Sphinx.

Can this be integrated with BOUT's documentation?

**Comment by d7919** [comment]
As it's a separate repository I'm not sure we will be able to embed the xBOUT documentation directly into the BOUT++ documentation. I think the best option is probably just to provide a prominent link from xBOUT's documentation to BOUT++'s documentation and vice-versa.

@ZedThree setup the documentation for BOUT++ using sphinx etc. so he's probably the best person to comment on this.

**Comment by TomNicholas** [comment]
Closed by #27
