### ISSUE TITLE
black-format everything

### ISSUE THREAD

**Issue by johnomotani** [boutproject/xBOUT#131]
Would be nice to format the whole repo with `black`, and add `black` as a PR-check. Need to do this at the point where it causes least pain with merging...

**Comment by ZedThree** [comment]
I'd be pretty tempted to `black`en everything, including PRs. That's probably the easiest way to reduce conflicts.

**Comment by ZedThree** [comment]
Also, there's a github action to apply `black` to a PR, might be useful

**Comment by johnomotani** [comment]
Done in #142.
