### ISSUE TITLE
matplotlib-3.3 compatibility

### ISSUE THREAD

**Issue by johnomotani** [boutproject/xBOUT#150]
There seem to be a couple of issues stopping xBOUT from working nicely with the latest matplotlib, v3.3.
* ~~animatplot doesn't work with `shading="nearest"` or `shading="gouraud"` https://github.com/t-makaro/animatplot/pull/53~~
* matplotlib animations in a Jupyter notebook (with the configuration I got by installing from conda-forge) freeze after playing through once https://github.com/matplotlib/matplotlib/issues/18580

The `animatplot` Github repo doesn't seem to be active any more. Maybe we should think about creating a fork where we can merge the various PRs that are currently open there, and require that for xBOUT.

**Comment by ianhi** [comment]
Just ended up here at the end of a pretty deep github rabbit hole so sorry if this is out of nowhere. 

>  Maybe we should think about creating a fork


I'd like to propose an alternative: I would be super open to PRs adding whatever functionality you need to my newish library mpl-interactions ([docs](https://mpl-interactions.readthedocs.io/en/latest/) - [github repo](https://github.com/ianhi/mpl-interactions)). 

Looking through the animatplot docs it looks as though we have a fairly different api, and our underlying model of how to interact with matplotlib is pretty different. However, having peeked through https://github.com/boutproject/xBOUT/blob/master/xbout/plotting/animate.py it looks like most of what you're using animatplot for could be accomplished already with mpl-interactions. I think you'd lose the ability to save animations, but that should be a quick add with the existing infrastructure. I recently (yesterday i think) added support for the `ipywidgets` play button and it shouldn't too hard to do what animatplot did to enable animated matplotlib sliders.




A few other miscellaneous thoughts:
1.  I haven't implemented pcolormesh yet but it's probably the most important of the pyplot functions I have not yet added (https://github.com/ianhi/mpl-interactions/issues/59)
2. It looks like animatplot is limited to only having one slider for a time axis. mpl-interactions generalizes to any number of parameters that can vary.
3. I don't know exactly how many parameter axes are normal in plasma simulations but we're creating a hyperstack slicer that will create sliders to scrub through a given array https://github.com/ianhi/mpl-interactions/pull/115
    - My use case multi position, multi channel, timelapse microscopy
    - Idea is you can just pass an (x)array in and it will correctly create sliders to scrub through the dimensions
3. I see you use `xarray`, one of my dreams is to have good integration with xarray for every function. I.e. where you pass in an xarray object and it uses the coordinates to create the sliders.


If you think it would be helpful to use mpl-interactions then please let me know and I'd be happy to chat more :)

**Comment by johnomotani** [comment]
@ianhi thanks for the info. Your library does look cool. I especially like the heatmap-comparison sliders! Animation-type functionality for xarray objects is also something we are very interested in.

Our development comes in fits and starts (when someone wants a feature enough to make the time to work on it!) but adding additional back-ends for animation is something I've started considering recently. Going to convert #147 into a general thread to discuss this...

**Comment by johnomotani** [comment]
The bug that made animations freeze should have been fixed by https://github.com/matplotlib/matplotlib/pull/18584. So should not be a problem once matplotlib-3.3.3 comes out. Until then either use matplotlib<3.3 or get the master branch from https://github.com/matplotlib/matplotlib/.

**Comment by johnomotani** [comment]
The animatplot problem should be fixed in the new 0.4.2 release.
