### ISSUE TITLE
Store git commit hash

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#16]
BOUT writes out the git commit hash of the compiled executable used into the log files. We could read this and store in the in the dataset `attrs`.

Ideally BOUT would be changed upstream so that it writes the commit hash into the dump files instead, so that xBOUT doesn't have to be given another filepath argument.

**Comment by johnomotani** [comment]
Hopefully this should happen automatically once https://github.com/boutproject/BOUT-dev/pull/1867 is merged in `BOUT-dev`.

**Comment by TomNicholas** [comment]
Can this be closed now?
