### ISSUE TITLE
Read grid file

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#17]
The BOUT grid file is just another netCDF file, but we should read it and merge it into the dataset.

Ideally BOUT would be changed upstream so that it writes the grid data into the dump files, so that `open_boutdataset()` doesn't need another filepath argument.

**Comment by d7919** [comment]
Not all simulations use a grid file so we'd have to be careful to make sure this was an optional feature (but could still be automatic if available). The other thing we'd have to be careful of is that often much of what is in the grid file ends up being written into the dump files but often with a different normalisation. As such we'd have to be careful that these duplicates are clearly distinct. 

I think this would rule out enforcing BOUT always writing the grid data into the dump files (at least in a simple way, we would have to disambiguate the raw grid data variable names). Secondly we only load information from the grid file on demand and don't currently explore/know all the variables that are available -- should we only write what we load or should we add functionality to read everything?

**Comment by rdoyle45** [comment]
Can this be closed due to the changes made in #33 ? @TomNicholas

**Comment by TomNicholas** [comment]
I think we can close it once the changes in #58 have been merged :)

**Comment by rdoyle45** [comment]
Close?

**Comment by johnomotani** [comment]
Resolved by #58.
