### ISSUE TITLE
Option to retain boundary/guard cells

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#19]
Currently `open_boutdataset()` will trim off all ghost cells, even at the outside edges of the domain. There should be an option to retain the guard cells at the edge of the domain.

This is not completely trivial because currently the [trimming is done](https://github.com/TomNicholas/xBOUT/blob/b50fe857776a0b6dfe63837d5e066e908de47af6/xbout/load.py#L20) by a `preprocess` argument to `open_boutdataset()`, so the same function is applied to every dataset. In order to know when to leave the guard cells untouched, the preprocess function has to know the position of the dataset it is currently operating on within the grid. Right now this isn't possible, but there are two ways it could be done:

1) Use the filename of the dataset to determine it's position, which would require a change upstream in xarray as discussed [here](https://github.com/pydata/xarray/issues/2550) . 

2) Get BOUT to write out the global position indexes to the dump files, which can then be used to work out the dataset's position in the grid. 

Another option is to not use the preprocess function at all, and instead concatenate all the untrimmed data then cut out the unwanted chunks from the result. I don't think this is the best solution however because then you aren't doing the trimming in parallel, it's not as clean conceptually, and it could break a lot of the tests.

I think the best solution would be to use global indexes once BOUT actually writes them out.

**Comment by d7919** [comment]
The outer guard cells are often really boundary cells and it's true that often you want to see these. Currently `collect` provides options to read the outer guard cells in any direction, it would be nice to maintain this functionality.

Option 2 relates to #3

**Comment by TomNicholas** [comment]
I just found [this issue](https://github.com/pydata/xarray/issues/1475) on the xarray repo describing how storing cell boundaries is an intended future addition to their data model. This would allow us to store the guard cells in this purpose-built way, so I'm writing this comment to point out that the guard cell handling should probably be changed once xarray does handle cell boundaries.

**Comment by TomNicholas** [comment]
@johnomotani will your work in #107 close this?

**Comment by johnomotani** [comment]
I think this was mostly fixed in #30 and #40. We could probably close this as done, and just note #113 as a bug in the current implementation.
