### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by d7919** [boutproject/xBOUT#2]
Should we setup Travis-CI so that we get automated testing?

**Comment by TomNicholas** [comment]
I think we should. Could also potentially use that bot that checks for PEP8 compliance, and coverage of tests?

**Comment by d7919** [comment]
@ZedThree has experience of setting up a variety of different integrations that should enable much of this.

**Comment by ZedThree** [comment]
Yes, I'll see how much of this I can get set up today

**Comment by TomNicholas** [comment]
I already added the pep8speaks bot so if someone submits a pull request we
can see if that works.
