### ISSUE TITLE
Reduce simplify required dependencies

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#22]
`xarray` and `dask` are obviously hard dependencies, but `animatplot` could be made optional by only importing it if you try to plot a gif, and `natsort` could possibly be eliminated by writing our own natural sorting function (instead of the call [here](https://github.com/TomNicholas/xBOUT/blob/b50fe857776a0b6dfe63837d5e066e908de47af6/xbout/load.py#L82)).

xBOUT also currently depends on a specific fork of xarray, and this should be merged as soon as possible so that we can just have a dependency on the master version of xarray.

**Comment by d7919** [comment]
Agreed that minimising hard dependencies is a good idea. We should also watch out for dependencies that require very recent versions of other libraries as this can cause problems for users less familiar with upgrading packages.

**Comment by TomNicholas** [comment]
So my multi-dimensional auto-combine [pull request](https://github.com/pydata/xarray/pull/2553) has just been merged into the master branch of xarray, so we don't need to rely on my fork anymore.

It will be altered further in future (currently it's essentially a "hidden feature" as we haven't decided on the best way to restructure the API), but we will now always be able to use xarray's master branch (and the stable branch after they do their next release). @ZedThree perhaps you want to alter this in the `setup.py`?

**Comment by johnomotani** [comment]
I think we can close this now. We are compatible with released versions of xarray, and the pip/conda compatibility simplifies installing the few dependencies we do have.
