### ISSUE TITLE
Can't open single file

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#24]
If you try to open only a single dump file with `open_boutdataset()`:

```python
ds = open_boutdataset('BOUT.dmp.0.nc')
```

then it will currently throw an error:

```
"Each run directory does not contain an equal number
of output files. If the parallelization scheme of 
your simulation changed partway-through, then please
load each directory separately and concatenate them
along the time dimension with xarray.concat()."
```

This is because it reads the processor parallelisation, then assumes that the the total number of processors divides the total number of files perfectly: 

```python
nprocs = nxpe * nype
n_runs = int(len(filepaths) / nprocs)
if len(filepaths) % nprocs != 0:
    raise ValueError("Each run directory... " 
```

We can either:

a) Remove this check, which makes the behaviour a bit less explicit.

b) Have a separate logical path for opening only one file. This then excludes the possibly of opening some other subset of all the files (like a single x row), but I don't know why you would want that. Also if you want to only open one file then you can always just use `xarray.open_dataset()` instead.

**Comment by johnomotani** [comment]
A different-but-related issue:
- say we run a simulation on (NXPE x NYPE) processors but squash the output into a single netcdf file, or (eventually) have parallel I/O and write a single file in the first place
- we probably want to keep NXPE and NYPE so we know how the simulation was run, but the number of files is no longer (NXPE x NYPE)
- at the moment `pylib/boutdata/collect.py` uses the filename: if there is a `<prefix>.<suffix>` file (e.g. `BOUT.dmp.nc`) it assumes this is the squashed/parallel output file and reads that, otherwise if the names are `<prefix>.*.<suffix>` it collects from the first (NXPE x NYPE) files.

I don't know what the best thing to do is; this is to flag that we need to be careful when assuming that the total number of processors divides the total number of files perfectly.

**Comment by TomNicholas** [comment]
Okay so after discussing with John, there seem to be 3 reasonable use cases which we should cover:

1) Opening all dump files across all processors and timesteps. 

2) Opening a single dump file to look at raw values for debugging purposes. 

3) Opening a set of datasets which originally came from BOUT dump files, but have since been resaved in some different structure.

(1) Is the main use case. We don't need to explicitly cover (2), because it can be done with bare xarray: 
```python
ds = xarray.open_dataset('BOUT.dmp.0.nc). 
```
(3) could be handled by checking the attributes of the first file for the presence (or absence) of some flag which indicates that this data is a raw BOUT dump file or not. If it is not, then we don't create the nested list of datasets, instead we just pass them all to `xarray.open_mfdataset()` as a flat list, which will attempt to "auto-magically" combine them using `xarray.auto_combine()` internally. This would be good for cases where someone saved different variables as different datasets to save space for example:
```
[density.nc, temperature.nc, potential.nc, ...]
```


Some other comments:

- If you want to look at physical results then lazy loading means there is not a lot of reason not to open the entire dataseries then slice it down, as it won't use any more memory. Opening the views to the data will take longer because `open_mfdataset()` will have to join up more files but I suggest we only worry about that if it turns out to be a significant bottleneck.

- It's worth pointing out that we could set the accessors up so that they can be called on datasets which were opened with `xarray.open_dataset()`, not just on datasets which were opened with `xbout.open_boutdataset()`. All we would need to do is catch the possibility that the metadata and options haven't yet been processed into the expected form:
```python
@register_dataset_accessor('bout')
class BoutDatasetAccessor:
    def __init__(self, ds):

        self.data = ds

        try:
            self.metadata = ds.attrs['metadata']
        except KeyError:
            warnings.warn('No metadata found')
            self.metadata = None
        # Same for options
        ...
```

- I haven't explicitly covered John's case of resaving with a different parallelisation but wanting to keep the provenance, is that particularly important?

**Comment by johnomotani** [comment]
I think it's enough to be able to open a single processor's dump file with `xarray.open_dataset`. So now that #51 is merged, we can close this?
