### ISSUE TITLE
bout.pcolormesh usage

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/xBOUT#247]
I am having trouble plotting using the `bout.pcolormesh`

It says to plot an R-Z slice, so I use something like:
```ds["Te"].isel(t=-1, y=0).bout.pcolormesh()```
but that fails as it expects `y` to be part of `da.dims`.
Not selecting `y=0` fails as `da` is 3d.

Is this not working with FCI? Am I doing something wrong?

`y` is orthogonal to the R-Z plane, thus I assumed that should be removed for plotting?

**Comment by johnomotani** [comment]
What you're doing I'd expect should work. I think this is probably just not working with FCI. When we wrote the poloidal-plane plotting we will have assumed that R and Z are functions of (x,y). I'm suspicious of this block, as `"bout_xdim"` and `"bout_ydim"` are used explicitly in several places (on a quick skim I think the rest of the plotting function should be OK...):
https://github.com/boutproject/xBOUT/blob/fe0e8eecb2966a1e7ef380a2c168891ef17f2000/xbout/plotting/plotfuncs.py#L299-L333
