### ISSUE TITLE
CI: Update actions

### ISSUE THREAD

**Issue by ZedThree** [boutproject/xBOUT#253]
Several issues:

- There's a separate workflow for the `master` branch -- can this just be merged into the main action?
- Master and publish workflows still run on Py3.7
- Publish workflow runs tests -- presumably at the point of making a new release, we've already run tests?
- Publish workflow should use `build` package instead of running `setup.py`
- Publish workflow should probably use API token instead of PYPI_PASSWORD
- `black` workflow is just check, but could be switched to auto-commit
- Various actions need versions bumping:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, codecov/codecov-action, actions/checkout

**Comment by dschwoerer** [comment]
>     * Publish workflow should probably use API token instead of PYPI_PASSWORD

I would assume PYPI_PASSWORD is already an API token?

>     * `black` workflow is just check, but could be switched to auto-commit

That would be great :+1:
