### ISSUE TITLE
Docs are failing to build PDFs

### ISSUE THREAD

**Issue by ZedThree** [boutproject/xBOUT#286]
See the [logs on readthedocs](https://readthedocs.org/projects/xbout/builds/19804638/). Relevant bit is this, I think:

```
LaTeX Warning: Hyper reference `xbout:xbout.load.open_boutdataset' on page 3 un
defined on input line 117.

[3] [4]
Chapter 2.

! LaTeX Error: Unknown graphics extension: .gif.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.139 ...ent\sphinxincludegraphics{{n_over_t}.gif}
                                                  

! LaTeX Error: Unknown graphics extension: .gif.
```

**Comment by johnomotani** [comment]
I guess the .gif is this page: https://xbout.readthedocs.io/en/latest/accessor_methods.html
Wonder what changed, as the .gif has always been there and the docs builds used to pass!

**Comment by dschwoerer** [comment]
It seems now the docs are failing for everything - rtd complains there is no config to be found ...

**Comment by ZedThree** [comment]
The docs are building again, but we're now not building the PDFs -- do we want to do so?

**Comment by johnomotani** [comment]
> The docs are building again, but we're now not building the PDFs -- do we want to do so?

I didn't know we ever were! I'd be happy to turn off building PDFs, I doubt anyone would ever use them.
