### ISSUE TITLE
open_grid is redundant

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#49]
Me and @johnomotani thought it would make sense to refactor so that `open_boutdataset` can also open a grid file, and discard `open_grid`. That's because if you have dump files, you *should* never actually need to open the grid file in addition. So as it's either grid OR dump files, we should just have one argument to `open_boutdataset`: `filepath`.

**Comment by rdoyle45** [comment]
@TomNicholas What would you suggest as a discriminating factor between grid and dump files?

**Comment by TomNicholas** [comment]
That dump files always have a `'t'` dimension, which grid files never will?

**Comment by bendudson** [comment]
Yes, `t` dimension is probably good for now. It's possible that at some time in the future someone may want to include a time-dependent source or other input in the grid file (moving grid?), but this is not currently supported by BOUT++ (and I think unlikely to be added soon).

**Comment by rdoyle45** [comment]
That would work well a discriminating factor (at least with BOUT++ in its current state). My concern would be that, if I'm not mistaken, for open_boutdataset to identify what file is to be read it must first open the file (in order to identify a t dimension). I can't seem to find any way around this at the moment.

**Comment by TomNicholas** [comment]
That's not a problem: `open_boutdataset` doesn't have to work out which file to open, you just specify that through the `filepath` argument. Then to know if that file is a grid file or not then you could just open it, check if it has a t dimension, close it, then hand off to the correct logic for a grid file or for dump files.

In fact we already do the open, check, close thing to determine processor splitting.

(If the dimensions aren't consistent between all the files then you should get an error later anyway)

**Comment by bendudson** [comment]
At some point (soon?) it would be good if there was less distinction between grid files and dump files: The dump files should contain the geometry/grid information, preferably in the same format as the grid files.

**Comment by TomNicholas** [comment]
That's was sort of the point of this issue right? I didn't originally realise that you can reconstruct the grid entirely from the dump files alone, which makes the grid file a lot less important. Or are you talking about upstream changes to BOUT?

**Comment by bendudson** [comment]
Yes, I mean upstream changes to BOUT++, sorry.

**Comment by rdoyle45** [comment]
> That's not a problem: `open_boutdataset` doesn't have to work out which file to open, you just specify that through the `filepath` argument. Then to know if that file is a grid file or not then you could just open it, check if it has a t dimension, close it, then hand off to the correct logic for a grid file or for dump files.
> 
> In fact we already do the open, check, close thing to determine processor splitting.
> 
> (If the dimensions aren't consistent between all the files then you should get an error later anyway)

Ah I see that now, thanks for clarifying Tom.
