### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#6]
xBOUT should be installable with pip. 

I don't know how that would work with the current dependency on a specific branch of a forked version of xarray (once it's merged that won't be an issue).

@ZedThree you said this was pretty simple?

**Comment by rdoyle45** [comment]
Would this be possible now @ZedThree?

**Comment by johnomotani** [comment]
`xBOUT` is now available through both `pip` and `conda`.
