### ISSUE TITLE
Binary files in repo

### ISSUE THREAD

**Issue by johnomotani** [boutproject/xBOUT#64]
There are some `.nc` files in the repo that were originally for testing, but are no longer needed as we create temporary files for tests. They make the repo ~70MB to download, so we should remove them. This requires re-writing the repo history, as described here
https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
It is recommended to do this with all PRs closed. We're aiming to do this before the BOUT++ workshop next week, before getting new users, as existing users will need to re-clone or reset/rebase their copies of xBOUT.

**Comment by rdoyle45** [comment]
All pull requests now closed

**Comment by johnomotani** [comment]
Thanks for merging everything @TomNicholas @rdoyle45!

I'll do this history re-write now. I'll fork a back-up onto my github before I do. Wouldn't hurt for you to do the same :-)

**Comment by johnomotani** [comment]
Done! Anyone planning to submit Pull Requests to xBOUT should now clone a fresh copy of the repo to ensure binary files don't get added back to the history by mistake.
