### ISSUE TITLE
Opening restarted runs returns data with duplicated timesteps

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#98]
When restarting a simulation, BOUT includes the initial timestep in the output, so when you open from multiple restarts (e.g. `open_boutdataset('./run*/BOUT.dmp.*.nc')`) the returned dataset has duplicated timesteps. These should be automatically dropped.

**Comment by johnomotani** [comment]
BTW there is an option `dump_on_restart` which can be set to false to avoid the duplicated timesteps being saved. This saves a small amount of disk space, but of course #99 is still useful in case the option was not set.

**Comment by TomNicholas** [comment]
Closed by #99
